#!/usr/bin/env bash
# run_schema_mirror_local.sh — Export runtime schema from local Odoo PG to repo artifacts.
#
# Produces runtime-derived artifacts in docs/data-model/runtime/ that complement
# the source-derived artifacts in docs/data-model/ (generated by scripts/generate_odoo_dbml.py).
#
# Usage:
#   ./scripts/dev/run_schema_mirror_local.sh
#
# Prerequisites:
#   - Local PostgreSQL running (localhost:5432, user: tbwa, db: odoo_dev)
#   - Python 3.12+ with psycopg2 installed
#   - OR: set ODOO_DB_* env vars to override defaults
#
# The script runs ONLY export_odoo_schema.py (which connects to Odoo PG directly).
# generate_dbml.py and validate_parity.py are Supabase-dependent and are skipped
# unless SUPABASE_DB_URL is set.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
MIRROR_DIR="${REPO_ROOT}/odoo-schema-mirror"
RUNTIME_DIR="${REPO_ROOT}/docs/data-model/runtime"
STAMP="$(date +%Y-%m-%dT%H:%M:%S%z)"

# --- Local PG defaults (per path-contract.md) ---
# Force local dev values. Shell may have stale DigitalOcean vars (deprecated 2026-03-15).
# To connect to Azure instead, pass env vars explicitly:
#   ODOO_DB_HOST=ipai-odoo-dev-pg.postgres.database.azure.com ./scripts/dev/run_schema_mirror_local.sh
if [[ "${1:-}" == "--azure" ]]; then
    # Azure mode: require env vars to be set externally
    : "${ODOO_DB_HOST:?ODOO_DB_HOST must be set for --azure mode}"
    : "${ODOO_DB_USER:?ODOO_DB_USER must be set for --azure mode}"
    : "${ODOO_DB_PASSWORD:?ODOO_DB_PASSWORD must be set for --azure mode}"
    export ODOO_DB_PORT="${ODOO_DB_PORT:-5432}"
    export ODOO_DB_NAME="${ODOO_DB_NAME:-postgres}"
else
    # Local mode: force canonical local dev values regardless of shell env
    export ODOO_DB_HOST="localhost"
    export ODOO_DB_PORT="5432"
    export ODOO_DB_NAME="odoo_dev"
    export ODOO_DB_USER="tbwa"
    export ODOO_DB_PASSWORD="${ODOO_DB_PASSWORD:-local}"  # Placeholder for peer/trust auth
fi

# Runtime artifacts go to a separate directory from source-derived artifacts
export SCHEMA_ARTIFACT_DIR="${RUNTIME_DIR}"

mkdir -p "${RUNTIME_DIR}"

echo "=== Schema Mirror: Local Runtime Export ==="
echo "Database: ${ODOO_DB_USER}@${ODOO_DB_HOST}:${ODOO_DB_PORT}/${ODOO_DB_NAME}"
echo "Output:   ${RUNTIME_DIR}"
echo "Stamp:    ${STAMP}"
echo ""

# --- Step 1: Export Odoo schema (Odoo PG → JSON) ---
echo "--- Step 1/3: export_odoo_schema.py ---"
if python3 "${MIRROR_DIR}/export_odoo_schema.py"; then
    echo "PASS: Schema exported to ${RUNTIME_DIR}/odoo_schema.json"
else
    echo "FAIL: export_odoo_schema.py exited $?"
    echo "Check: is PostgreSQL running? is odoo_dev database initialized?"
    exit 1
fi

# --- Step 2: generate_dbml.py (Supabase-dependent — skip unless configured) ---
echo ""
echo "--- Step 2/3: generate_dbml.py ---"
if [[ -n "${SUPABASE_DB_URL:-}" ]]; then
    export DBML_OUTPUT_DIR="${RUNTIME_DIR}"
    if python3 "${MIRROR_DIR}/generate_dbml.py"; then
        echo "PASS: DBML generated from Supabase shadow schema"
    else
        echo "WARN: generate_dbml.py failed (non-fatal)"
    fi
else
    echo "SKIP: SUPABASE_DB_URL not set — generate_dbml.py requires Supabase odoo_shadow schema"
    echo "      Source-derived DBML is available at docs/data-model/ODOO_CANONICAL_SCHEMA.dbml"
fi

# --- Step 3: validate_parity.py (needs both DBs — skip unless configured) ---
echo ""
echo "--- Step 3/3: validate_parity.py ---"
if [[ -n "${SUPABASE_DB_URL:-}" ]]; then
    if python3 "${MIRROR_DIR}/validate_parity.py"; then
        echo "PASS: Parity validation complete"
    else
        echo "WARN: validate_parity.py failed (non-fatal)"
    fi
else
    echo "SKIP: SUPABASE_DB_URL not set — parity validation requires both Odoo PG and Supabase"
fi

# --- Summary ---
echo ""
echo "=== Runtime Schema Mirror Complete ==="
echo "Artifacts:"
ls -lh "${RUNTIME_DIR}/" 2>/dev/null || echo "  (no artifacts produced)"
echo ""
echo "Timestamp: ${STAMP}"

# Write manifest for drift detection
cat > "${RUNTIME_DIR}/manifest.json" <<MANIFEST
{
  "generated_at": "${STAMP}",
  "source_db": "${ODOO_DB_NAME}",
  "source_host": "${ODOO_DB_HOST}",
  "source_port": ${ODOO_DB_PORT},
  "generator": "scripts/dev/run_schema_mirror_local.sh",
  "toolkit": "odoo-schema-mirror/",
  "steps": {
    "export_odoo_schema": "executed",
    "generate_dbml": "$(if [[ -n "${SUPABASE_DB_URL:-}" ]]; then echo executed; else echo skipped; fi)",
    "validate_parity": "$(if [[ -n "${SUPABASE_DB_URL:-}" ]]; then echo executed; else echo skipped; fi)"
  }
}
MANIFEST

echo "Manifest: ${RUNTIME_DIR}/manifest.json"
