// =============================================================================
// SERVE-ERD - Entity Relationship Diagram Server
// =============================================================================
// Purpose: Serve auto-generated ERD artifacts from Supabase Storage
// Endpoints:
//   GET /serve-erd?format=svg&filter=ipai  (serve specific ERD)
//   GET /serve-erd                          (serve default full ERD)
//
// This function serves ERD diagrams stored in Supabase Storage bucket 'erd'.
// ERDs are auto-generated by CI/CD and uploaded to storage.
//
// Query Parameters:
//   - format: svg|png|dot (default: svg)
//   - filter: ipai|db|<prefix> (default: none, serves full ERD)
//   - version: latest|<timestamp> (default: latest)
//
// Headers:
//   - Cache-Control: public, max-age=3600 (1 hour cache)
//   - CORS headers for Superset embedding
// =============================================================================

import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

interface ERDRequest {
  format: "svg" | "png" | "dot";
  filter: string | null;
  version: string;
}

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
};

const contentTypes: Record<string, string> = {
  svg: "image/svg+xml",
  png: "image/png",
  dot: "text/plain",
};

const cacheHeaders = {
  "Cache-Control": "public, max-age=3600, stale-while-revalidate=86400",
};

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

function parseRequest(url: URL): ERDRequest {
  const format = (url.searchParams.get("format") || "svg") as ERDRequest["format"];
  const filter = url.searchParams.get("filter");
  const version = url.searchParams.get("version") || "latest";

  // Validate format
  if (!["svg", "png", "dot"].includes(format)) {
    throw new Error(`Invalid format: ${format}. Use svg, png, or dot.`);
  }

  return { format, filter, version };
}

function buildFilename(request: ERDRequest): string {
  const { format, filter, version } = request;

  let basename = "ODOO_ERD";
  if (filter) {
    basename = `ODOO_ERD_${filter}`;
  }

  if (version !== "latest") {
    basename = `${basename}_${version}`;
  }

  return `${basename}.${format}`;
}

function errorResponse(message: string, status = 400): Response {
  return new Response(JSON.stringify({ ok: false, error: message }), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

// -----------------------------------------------------------------------------
// Main Handler
// -----------------------------------------------------------------------------

serve(async (req: Request) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  // Only accept GET
  if (req.method !== "GET") {
    return errorResponse("Method not allowed. Use GET.", 405);
  }

  try {
    const url = new URL(req.url);
    const request = parseRequest(url);
    const filename = buildFilename(request);

    // Initialize Supabase client
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

    if (!supabaseUrl || !supabaseKey) {
      return errorResponse("Supabase credentials not configured", 500);
    }

    const supabase = createClient(supabaseUrl, supabaseKey);

    // Try to download from storage
    const { data, error } = await supabase.storage.from("erd").download(filename);

    if (error) {
      // Check if it's a not found error
      if (error.message?.includes("not found") || error.message?.includes("404")) {
        // Try alternate filenames
        const altFilenames = [
          `latest/${filename}`,
          filename.replace("ODOO_ERD", "erd"),
          `docs/data-model/${filename}`,
        ];

        for (const altFilename of altFilenames) {
          const { data: altData, error: altError } = await supabase.storage
            .from("erd")
            .download(altFilename);

          if (!altError && altData) {
            const contentType = contentTypes[request.format] || "application/octet-stream";
            return new Response(altData, {
              headers: {
                ...corsHeaders,
                ...cacheHeaders,
                "Content-Type": contentType,
                "X-ERD-Source": `erd/${altFilename}`,
              },
            });
          }
        }

        return errorResponse(
          `ERD not found: ${filename}. Available files may include: ODOO_ERD.svg, ODOO_ERD_ipai.svg`,
          404
        );
      }

      return errorResponse(`Storage error: ${error.message}`, 500);
    }

    const contentType = contentTypes[request.format] || "application/octet-stream";

    return new Response(data, {
      headers: {
        ...corsHeaders,
        ...cacheHeaders,
        "Content-Type": contentType,
        "X-ERD-Source": `erd/${filename}`,
        "X-ERD-Generated": new Date().toISOString(),
      },
    });
  } catch (error) {
    console.error("serve-erd error:", error);
    return errorResponse(error.message || "Internal server error", 500);
  }
});
