// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(app)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(app)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/backups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/backups">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/backups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/branches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/branches">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/branches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/builds/[buildId]/editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/builds/[buildId]/editor">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/builds/[buildId]/editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/builds/[buildId]/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/builds/[buildId]/logs">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/builds/[buildId]/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/builds/[buildId]/monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/builds/[buildId]/monitor">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/builds/[buildId]/monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/builds/[buildId]/shell/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/builds/[buildId]/shell">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/builds/[buildId]/shell/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/builds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/builds">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/builds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/monitor">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/settings">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/upgrade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/upgrade">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/upgrade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/close/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/close/audit">> = Specific
  const handler = {} as typeof import("../../app/app/close/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/close/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/close/compliance">> = Specific
  const handler = {} as typeof import("../../app/app/close/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/close/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/close">> = Specific
  const handler = {} as typeof import("../../app/app/close/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/close/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/close/tasks">> = Specific
  const handler = {} as typeof import("../../app/app/close/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/logout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logout">> = Specific
  const handler = {} as typeof import("../../app/logout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/supabase-proxy/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/supabase-proxy/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/supabase-proxy/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/builds/[buildId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/projects/[projectId]/builds/[buildId]">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/builds/[buildId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
