#!/usr/bin/env python3
"""
File-based Jinja2 templates with Environment.

Demonstrates:
- Loading templates from files
- Environment configuration
- Rendering from template files
"""
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

# Setup template environment
templates_dir = Path(__file__).parent / "templates"
templates_dir.mkdir(exist_ok=True)

# Create a sample template file
sample_template = templates_dir / "report.html.j2"
sample_template.write_text("""<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <p>Generated for: {{ recipient }}</p>

    <h2>Items</h2>
    <ul>
    {% for item in items %}
        <li>{{ item.name }}: {{ item.value }}</li>
    {% endfor %}
    </ul>

    {% if footer %}
    <footer>{{ footer }}</footer>
    {% endif %}
</body>
</html>
""")

# Create environment with common settings
env = Environment(
    loader=FileSystemLoader(str(templates_dir)),
    autoescape=True,       # Safe for HTML
    trim_blocks=True,      # Remove newline after blocks
    lstrip_blocks=True     # Strip whitespace before blocks
)

# Load and render template
template = env.get_template("report.html.j2")
result = template.render(
    title="Monthly Report",
    recipient="Finance Team",
    items=[
        {"name": "Revenue", "value": "$125,000"},
        {"name": "Expenses", "value": "$98,000"},
        {"name": "Net Income", "value": "$27,000"}
    ],
    footer="Generated by IPAI System"
)

print("Rendered HTML:")
print(result)

# Cleanup
sample_template.unlink()
templates_dir.rmdir()
