#!/usr/bin/env bash
# Example: Assess odo usage request
set -euo pipefail

echo "=== Assessing odo ==="
echo "Tool: odo (Red Hat OpenShift Developer CLI)"
echo "Status: Officially deprecated"
echo "GitHub: Archived (https://github.com/redhat-developer/odo)"
echo ""
echo "Assessment:"
echo "  Verdict: REJECT"
echo "  Reason: Officially deprecated by Red Hat. No active maintenance."
echo "  Alternative: No direct replacement needed — IPAI does not use OpenShift."
echo "  For data/ML: Use Databricks CLI"
echo "  For infrastructure: Use Azure CLI (az) or azd"
echo "  For ERP: Use Odoo CLI (odoo-bin)"
echo ""
echo "Exception criteria evaluation:"
echo "  1. No canonical alternative for specific operation: N/A — no operation requires odo"
echo "  2. Only path to business outcome: FALSE — all outcomes achievable via canonical tools"
echo "  3. Time-boxed: N/A"
echo "  4. Documented exception: N/A"
echo "  5. Migration plan filed: N/A"
echo ""
echo "Final: PERMANENT REJECT — no exception pathway"
