export interface DesignerAgentEnv {
  AZURE_FOUNDRY_ENDPOINT: string;
  AZURE_FOUNDRY_PROJECT_CONNECTION_STRING?: string;
  AZURE_FOUNDRY_MODEL_DEPLOYMENT?: string;
  AZURE_FOUNDRY_DESIGNER_AGENT_ID?: string;
  AZURE_FOUNDRY_DESIGNER_AGENT_NAME: string;
  DESIGNER_AGENT_TIMEOUT_MS: string;
}

export function readDesignerAgentEnv(env: NodeJS.ProcessEnv): DesignerAgentEnv {
  if (!env.AZURE_FOUNDRY_ENDPOINT) {
    throw new Error('AZURE_FOUNDRY_ENDPOINT is required');
  }
  if (!env.AZURE_FOUNDRY_DESIGNER_AGENT_NAME) {
    throw new Error('AZURE_FOUNDRY_DESIGNER_AGENT_NAME is required');
  }

  return {
    AZURE_FOUNDRY_ENDPOINT: env.AZURE_FOUNDRY_ENDPOINT,
    AZURE_FOUNDRY_PROJECT_CONNECTION_STRING: env.AZURE_FOUNDRY_PROJECT_CONNECTION_STRING,
    AZURE_FOUNDRY_MODEL_DEPLOYMENT: env.AZURE_FOUNDRY_MODEL_DEPLOYMENT,
    AZURE_FOUNDRY_DESIGNER_AGENT_ID: env.AZURE_FOUNDRY_DESIGNER_AGENT_ID,
    AZURE_FOUNDRY_DESIGNER_AGENT_NAME: env.AZURE_FOUNDRY_DESIGNER_AGENT_NAME,
    DESIGNER_AGENT_TIMEOUT_MS: env.DESIGNER_AGENT_TIMEOUT_MS ?? '45000',
  };
}
