#!/usr/bin/env python3
"""
skills-build (Python)

Adopts the Agent Skills Open Standard patterns:
- SKILL.md has YAML frontmatter (name, description, optional metadata)
- references/ contains modular docs with progressive disclosure
- AGENTS.md is generated/compiled for fast agent consumption

This script:
1) Finds skills under:
   - .claude/skills/*
   - .claude/superclaude/skills/**/*
2) Validates SKILL.md has required frontmatter keys (name, description)
3) Generates AGENTS.md per skill by concatenating references/*.md (if present)
4) Supports --check to fail on drift (CI gate)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any, Dict, List


FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)

SKILL_ROOTS = [
    Path(".claude/skills"),
    Path(".claude/superclaude/skills"),
]


def read_text(p: Path) -> str:
    return p.read_text(encoding="utf-8")


def write_if_changed(p: Path, content: str) -> bool:
    existing = p.read_text(encoding="utf-8") if p.exists() else ""
    if existing == content:
        return False
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return True


def parse_frontmatter(skill_md: str) -> Dict[str, Any]:
    m = FRONTMATTER_RE.match(skill_md)
    if not m:
        raise ValueError("Missing YAML frontmatter (--- ... ---) at top of SKILL.md")
    block = m.group(1)
    try:
        import yaml  # type: ignore
    except Exception as e:
        raise RuntimeError("PyYAML required: pip install pyyaml") from e
    data = yaml.safe_load(block) or {}
    if not isinstance(data, dict):
        raise ValueError("Frontmatter must parse to a mapping/object")
    return data


def find_skill_dirs() -> List[Path]:
    dirs: List[Path] = []
    for r in SKILL_ROOTS:
        if not r.exists():
            continue
        for skill_md in r.rglob("SKILL.md"):
            dirs.append(skill_md.parent)
    return sorted(set(dirs))


def collect_references(skill_dir: Path) -> List[Path]:
    ref_dir = skill_dir / "references"
    if not ref_dir.exists():
        return []
    refs = [
        p
        for p in sorted(ref_dir.rglob("*.md"), key=lambda p: p.as_posix())
        if p.is_file() and not p.name.startswith("_")
    ]
    return refs


def build_agents_md(skill_dir: Path, fm: Dict[str, Any], refs: List[Path]) -> str:
    name = str(fm.get("name", "")).strip()
    desc = str(fm.get("description", "")).strip()
    version = str(fm.get("version", "")).strip()
    tags = fm.get("tags", [])

    lines: List[str] = [
        f"# {name}",
        "",
        f"> {desc}",
        "",
    ]
    if version:
        lines.append(f"**Version:** {version}")
    if tags:
        lines.append(f"**Tags:** {', '.join(str(t) for t in tags)}")
    if version or tags:
        lines.append("")
    lines += [
        "---",
        "",
        "_This file is generated by `scripts/skills/build_skills.py`. Do not edit by hand._",
        "",
    ]

    if not refs:
        lines.append(
            "_No references/ directory found. "
            "Add modular docs under references/*.md for progressive disclosure._"
        )
        lines.append("")
        return "\n".join(lines)

    for p in refs:
        rel = p.relative_to(skill_dir).as_posix()
        lines.append(f"## {rel}")
        lines.append("")
        lines.append(read_text(p).rstrip())
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Build and validate agent skills")
    ap.add_argument("--check", action="store_true", help="Fail if AGENTS.md would change")
    args = ap.parse_args()

    skill_dirs = find_skill_dirs()
    if not skill_dirs:
        sys.stderr.write(
            "No skills found under .claude/skills or .claude/superclaude/skills\n"
        )
        return 0

    errors: List[str] = []
    drift = False

    for d in skill_dirs:
        skill_md = d / "SKILL.md"
        agents_md = d / "AGENTS.md"
        rel = d.as_posix()

        try:
            fm = parse_frontmatter(read_text(skill_md))

            for k in ("name", "description"):
                if not str(fm.get(k, "")).strip():
                    raise ValueError(f"Frontmatter missing required key: {k}")

            refs = collect_references(d)
            rendered = build_agents_md(d, fm, refs)

            if args.check:
                existing = read_text(agents_md) if agents_md.exists() else ""
                if existing != rendered:
                    sys.stderr.write(f"  drift: {rel}/AGENTS.md\n")
                    drift = True
            else:
                changed = write_if_changed(agents_md, rendered)
                if changed:
                    sys.stderr.write(f"  updated: {rel}/AGENTS.md\n")

        except Exception as e:
            errors.append(f"{rel}: {e}")

    if errors:
        sys.stderr.write(
            "skills-build errors:\n" + "\n".join(f"  - {x}" for x in errors) + "\n"
        )
        return 2

    if args.check and drift:
        sys.stderr.write(
            "AGENTS.md drift detected. Run: python scripts/skills/build_skills.py\n"
        )
        return 3

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
