{
    "name": "IPAI PPM A1 (AFC + STC Control Center)",
    "version": "18.0.1.0.0",
    "category": "Accounting/Accounting",
    "summary": "Odoo-native A1 assistant for AFC financial close + STC tax compliance: templates, tasks, checks, overlays, import/export seeds.",
    "depends": ["base", "mail", "project"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequences.xml",
        "data/cron.xml",
        "views/menu.xml",
        "views/workstream_views.xml",
        "views/template_views.xml",
        "views/task_views.xml",
        "views/tasklist_views.xml",
        "views/compliance_views.xml",
        "views/overlay_views.xml",
        "views/export_run_views.xml",
        "views/wizard_views.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
