-- Migration: Finance PPM Monthly Reports Table
-- Purpose: Archive monthly compliance reports generated by n8n workflows
-- Dependencies: ipai_finance_ppm Odoo module

-- Create schema if not exists
CREATE SCHEMA IF NOT EXISTS finance_ppm;

-- Monthly compliance reports table
CREATE TABLE IF NOT EXISTS finance_ppm.monthly_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    period VARCHAR(7) NOT NULL,  -- Format: YYYY-MM (e.g., "2025-11")
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Statistics
    total_forms INTEGER NOT NULL,
    filed_on_time INTEGER NOT NULL,
    late_filings INTEGER NOT NULL,
    compliance_rate DECIMAL(5,2) NOT NULL,  -- Percentage (0.00-100.00)
    avg_completion DECIMAL(5,2) NOT NULL,   -- Percentage (0.00-100.00)

    -- Status breakdown
    status_not_started INTEGER DEFAULT 0,
    status_in_progress INTEGER DEFAULT 0,
    status_submitted INTEGER DEFAULT 0,
    status_filed INTEGER DEFAULT 0,

    -- Report content
    report_markdown TEXT NOT NULL,  -- Full markdown report
    recommendations TEXT[],          -- Array of recommendation strings

    -- Metadata
    workflow_id VARCHAR(100),        -- n8n workflow ID
    execution_id VARCHAR(100),       -- n8n execution ID
    alert_sent BOOLEAN DEFAULT FALSE,
    finance_director_notified BOOLEAN DEFAULT FALSE,

    -- Audit fields
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT unique_period UNIQUE(period),
    CONSTRAINT valid_compliance_rate CHECK (compliance_rate >= 0 AND compliance_rate <= 100),
    CONSTRAINT valid_avg_completion CHECK (avg_completion >= 0 AND avg_completion <= 100),
    CONSTRAINT valid_totals CHECK (
        total_forms = (status_not_started + status_in_progress + status_submitted + status_filed)
    )
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_monthly_reports_period ON finance_ppm.monthly_reports(period DESC);
CREATE INDEX IF NOT EXISTS idx_monthly_reports_generated_at ON finance_ppm.monthly_reports(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_monthly_reports_compliance_rate ON finance_ppm.monthly_reports(compliance_rate);
CREATE INDEX IF NOT EXISTS idx_monthly_reports_alert_sent ON finance_ppm.monthly_reports(alert_sent) WHERE alert_sent = TRUE;

-- Updated timestamp trigger
CREATE OR REPLACE FUNCTION finance_ppm.update_monthly_reports_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_monthly_reports_timestamp
    BEFORE UPDATE ON finance_ppm.monthly_reports
    FOR EACH ROW
    EXECUTE FUNCTION finance_ppm.update_monthly_reports_timestamp();

-- Row Level Security (RLS)
ALTER TABLE finance_ppm.monthly_reports ENABLE ROW LEVEL SECURITY;

-- Policy: Allow service role full access
CREATE POLICY "Service role has full access to monthly_reports"
    ON finance_ppm.monthly_reports
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Policy: Authenticated users can read reports
CREATE POLICY "Authenticated users can read monthly_reports"
    ON finance_ppm.monthly_reports
    FOR SELECT
    TO authenticated
    USING (true);

-- Grant permissions
GRANT USAGE ON SCHEMA finance_ppm TO service_role, authenticated;
GRANT ALL ON finance_ppm.monthly_reports TO service_role;
GRANT SELECT ON finance_ppm.monthly_reports TO authenticated;

-- Comments for documentation
COMMENT ON TABLE finance_ppm.monthly_reports IS 'Archives monthly Finance PPM compliance reports generated by n8n workflows';
COMMENT ON COLUMN finance_ppm.monthly_reports.period IS 'Report period in YYYY-MM format (e.g., 2025-11)';
COMMENT ON COLUMN finance_ppm.monthly_reports.compliance_rate IS 'Percentage of forms filed on time (0.00-100.00)';
COMMENT ON COLUMN finance_ppm.monthly_reports.report_markdown IS 'Full markdown-formatted compliance report';
COMMENT ON COLUMN finance_ppm.monthly_reports.recommendations IS 'Array of actionable recommendations';
COMMENT ON COLUMN finance_ppm.monthly_reports.finance_director_notified IS 'True if urgent alert was sent to Finance Director';

-- Validation query (run after migration)
-- SELECT
--     schemaname, tablename, tableowner, hasindexes, hasrules, hastriggers
-- FROM pg_tables
-- WHERE schemaname = 'finance_ppm' AND tablename = 'monthly_reports';
