{
    "name": "IPAI PPM Dashboard Canvas",
    "version": "18.0.1.0.0",
    "category": "Project",
    "summary": "Clarity Canvas-style Project Dashboard with phases, milestones, tasks, to-dos, and OKR views",
    "author": "InsightPulse AI",
    "license": "LGPL-3",
    "depends": [
        "project",
        "mail",
        "web",
        "hr_timesheet",
    ],
    "data": [
        "views/ppm_dashboard_menus.xml",
        "views/project_project_canvas_views.xml",
        "views/project_task_canvas_views.xml",
        "views/project_milestone_canvas_views.xml",
        "views/project_todo_canvas_views.xml",
        "views/ppm_dashboard_actions.xml",
        "views/ppm_dashboard_search_views.xml",
        "views/ppm_dashboard_pivot_graph_views.xml",
        "views/okr_views.xml",
    ],
    "installable": True,
    "application": False,
}
