Resources
| where type in (
    "microsoft.app/containerapps",
    "microsoft.compute/virtualmachines",
    "microsoft.storage/storageaccounts"
  )
| join kind=leftouter (
    ResourceChanges
    | where properties.changeAttributes.timestamp > ago(30d)
    | summarize lastChange=max(properties.changeAttributes.timestamp)
              by resourceId=properties.targetResourceId
  ) on $left.id == $right.resourceId
| where isnull(lastChange)
| project name, type, resourceGroup, location
