#!/usr/bin/env bash
# scripts/teams/package-apps.sh
#
# Zips each agents/<name>-surface/appPackage/ into a Teams-uploadable
# manifest bundle. Output: agents/<name>-surface/appPackage/build/app.<env>.zip
#
# Prereqs: manifest.json, color.png, outline.png must exist in appPackage/.
# Icons: generated by `python3 scripts/teams/gen-teams-icons.py` (see repo).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ENV="${TEAMSFX_ENV:-dev}"

AGENTS=(
  teams-surface
  tax-guru-surface
  doc-intel-surface
  bank-recon-surface
  ap-invoice-surface
  finance-close-surface
)

for name in "${AGENTS[@]}"; do
  pkg_dir="${REPO_ROOT}/agents/${name}/appPackage"
  build_dir="${pkg_dir}/build"
  out="${build_dir}/app.${ENV}.zip"

  if [ ! -f "${pkg_dir}/manifest.json" ]; then
    echo "SKIP ${name}: missing manifest.json"
    continue
  fi
  if [ ! -f "${pkg_dir}/color.png" ] || [ ! -f "${pkg_dir}/outline.png" ]; then
    echo "SKIP ${name}: missing color.png or outline.png"
    continue
  fi

  mkdir -p "${build_dir}"
  rm -f "${out}"

  # Zip manifest + icons only. No extra files.
  (cd "${pkg_dir}" && zip -q "${out}" manifest.json color.png outline.png)
  size=$(stat -f%z "${out}" 2>/dev/null || stat -c%s "${out}")
  echo "OK   ${name}: ${out} (${size}B)"
done
