#!/usr/bin/env bash
# =============================================================================
# azure_estate_audit.sh — Coverage-driven Azure estate inventory & drift gate
# =============================================================================
# Queries every authoritative resource type defined in
# ssot/azure/estate_coverage.yaml using targeted per-type API calls.
#
# Does NOT rely on generic az resource list (RBAC-filtered, unreliable).
#
# Outputs:
#   .artifacts/azure-estate/estate-<timestamp>.yaml   (full inventory)
#   .artifacts/azure-estate/estate-latest.yaml        (symlink)
#   .artifacts/azure-estate/drift-report.txt          (vs expected baseline)
#   .artifacts/azure-estate/coverage-report.txt       (type coverage summary)
#
# Exit codes:
#   0 = no critical drift
#   1 = critical authoritative resource missing (pipeline FAIL)
# =============================================================================
set -euo pipefail

TIMESTAMP=$(date -u +%Y%m%dT%H%M%SZ)
OUT_DIR=".artifacts/azure-estate"
ESTATE_FILE="${OUT_DIR}/estate-${TIMESTAMP}.yaml"
LATEST_LINK="${OUT_DIR}/estate-latest.yaml"
DRIFT_FILE="${OUT_DIR}/drift-report.txt"
COVERAGE_REPORT="${OUT_DIR}/coverage-report.txt"
EXPECTED="ssot/azure/expected-estate.yaml"
COVERAGE_POLICY="ssot/azure/estate_coverage.yaml"

mkdir -p "${OUT_DIR}"

EXIT_CODE=0

# =========================================================================
# 1. Subscription context
# =========================================================================
SUB=$(az account show -o json 2>&1)
SUB_NAME=$(echo "$SUB" | jq -r '.name')
SUB_ID=$(echo "$SUB" | jq -r '.id')
TENANT_ID=$(echo "$SUB" | jq -r '.tenantId')

cat > "${ESTATE_FILE}" <<EOF
# Azure Estate Audit — ${TIMESTAMP}
# Generated by scripts/ci/azure_estate_audit.sh
# Coverage policy: ssot/azure/estate_coverage.yaml
# Authority model: ssot/azure/estate_authority.yaml

subscription:
  name: "${SUB_NAME}"
  id: "${SUB_ID}"
  tenant: "${TENANT_ID}"
  queried_at: "${TIMESTAMP}"

EOF

# =========================================================================
# 2. Resource groups
# =========================================================================
echo "resource_groups:" >> "${ESTATE_FILE}"
az group list --query "[].{name:name, location:location}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    location: \"\(.location)\""' >> "${ESTATE_FILE}"
echo "" >> "${ESTATE_FILE}"

# =========================================================================
# 3. Generic API count (diagnostic only — NOT authoritative)
# =========================================================================
GENERIC_COUNT=0
for rg in $(az group list --query "[].name" -o tsv 2>/dev/null); do
  C=$(az resource list -g "$rg" --query "length(@)" -o tsv 2>/dev/null || echo 0)
  GENERIC_COUNT=$((GENERIC_COUNT + C))
done

# =========================================================================
# 4. Authoritative type queries (Tier A)
#    Each block corresponds to a query_key in estate_coverage.yaml.
#    Adding a new authoritative type requires adding a block here AND
#    a row in estate_coverage.yaml.
# =========================================================================
echo "# ======================================" >> "${ESTATE_FILE}"
echo "# Tier A — Authoritative service estate" >> "${ESTATE_FILE}"
echo "# ======================================" >> "${ESTATE_FILE}"
echo "" >> "${ESTATE_FILE}"

# --- container_apps ---
echo "container_apps:" >> "${ESTATE_FILE}"
az containerapp list --query "[].{name:name, rg:resourceGroup, state:properties.provisioningState}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\"\n    state: \"\(.state)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
echo "" >> "${ESTATE_FILE}"

# --- container_app_environments ---
echo "container_app_environments:" >> "${ESTATE_FILE}"
az containerapp env list --query "[].{name:name, rg:resourceGroup}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
echo "" >> "${ESTATE_FILE}"

# --- container_app_jobs ---
echo "container_app_jobs:" >> "${ESTATE_FILE}"
az containerapp job list --query "[].{name:name, rg:resourceGroup}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
echo "" >> "${ESTATE_FILE}"

# --- function_apps ---
echo "function_apps:" >> "${ESTATE_FILE}"
az functionapp list --query "[].{name:name, rg:resourceGroup, state:state}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\"\n    state: \"\(.state)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
echo "" >> "${ESTATE_FILE}"

# --- postgresql_servers ---
echo "postgresql_servers:" >> "${ESTATE_FILE}"
for rg in $(az group list --query "[].name" -o tsv 2>/dev/null); do
  az postgres flexible-server list -g "$rg" --query "[].{name:name, state:state, version:version, sku:sku.name}" -o json 2>/dev/null | \
    jq -r --arg rg "$rg" '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\($rg)\"\n    state: \"\(.state)\"\n    version: \"\(.version)\"\n    sku: \"\(.sku)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
done
echo "" >> "${ESTATE_FILE}"

# --- key_vaults ---
echo "key_vaults:" >> "${ESTATE_FILE}"
KV_FOUND=false
az keyvault list --query "[].{name:name, rg:resourceGroup, uri:properties.vaultUri}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\"\n    uri: \"\(.uri)\""' >> "${ESTATE_FILE}" 2>/dev/null && KV_FOUND=true || true
# Fallback for RBAC-filtered keyvault list
if [ "$KV_FOUND" = false ] || ! grep -q 'kv-ipai-dev' "${ESTATE_FILE}" 2>/dev/null; then
  for kv in kv-ipai-dev; do
    for rg in rg-ipai-dev-platform rg-ipai-dev-odoo-runtime; do
      RESULT=$(az keyvault show --name "$kv" --resource-group "$rg" --query "{name:name, uri:properties.vaultUri}" -o json 2>/dev/null || true)
      if [ -n "$RESULT" ] && [ "$RESULT" != "null" ] && echo "$RESULT" | jq -e '.name' >/dev/null 2>&1; then
        echo "$RESULT" | jq -r --arg rg "$rg" '"  - name: \"\(.name)\"\n    resource_group: \"\($rg)\"\n    uri: \"\(.uri)\""' >> "${ESTATE_FILE}"
      fi
    done
  done
fi
echo "" >> "${ESTATE_FILE}"

# --- container_registries ---
echo "container_registries:" >> "${ESTATE_FILE}"
az acr list --query "[].{name:name, rg:resourceGroup, loginServer:loginServer}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\"\n    login_server: \"\(.loginServer)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
echo "" >> "${ESTATE_FILE}"

# --- front_doors ---
echo "front_doors:" >> "${ESTATE_FILE}"
az afd profile list --query "[].{name:name, rg:resourceGroup, sku:sku.name}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\"\n    sku: \"\(.sku)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
echo "" >> "${ESTATE_FILE}"

# --- waf_policies ---
echo "waf_policies:" >> "${ESTATE_FILE}"
for rg in $(az group list --query "[].name" -o tsv 2>/dev/null); do
  az network front-door waf-policy list -g "$rg" --query "[].{name:name}" -o json 2>/dev/null | \
    jq -r --arg rg "$rg" '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\($rg)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
done
echo "" >> "${ESTATE_FILE}"

# --- virtual_networks ---
echo "virtual_networks:" >> "${ESTATE_FILE}"
az network vnet list --query "[].{name:name, rg:resourceGroup, addressSpace:addressSpace.addressPrefixes[0]}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\"\n    address_space: \"\(.addressSpace)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
echo "" >> "${ESTATE_FILE}"

# --- dns_zones ---
echo "dns_zones:" >> "${ESTATE_FILE}"
az network dns zone list --query "[].{name:name, rg:resourceGroup}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
echo "" >> "${ESTATE_FILE}"

# --- private_dns_zones ---
echo "private_dns_zones:" >> "${ESTATE_FILE}"
az network private-dns zone list --query "[].{name:name, rg:resourceGroup}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
echo "" >> "${ESTATE_FILE}"

# --- private_endpoints ---
echo "private_endpoints:" >> "${ESTATE_FILE}"
az network private-endpoint list --query "[].{name:name, rg:resourceGroup}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
echo "" >> "${ESTATE_FILE}"

# --- application_insights ---
echo "application_insights:" >> "${ESTATE_FILE}"
for rg in $(az group list --query "[].name" -o tsv 2>/dev/null); do
  az resource list -g "$rg" --resource-type "Microsoft.Insights/components" --query "[].{name:name}" -o json 2>/dev/null | \
    jq -r --arg rg "$rg" '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\($rg)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
done
echo "" >> "${ESTATE_FILE}"

# --- log_analytics_workspaces ---
echo "log_analytics_workspaces:" >> "${ESTATE_FILE}"
az monitor log-analytics workspace list --query "[].{name:name, rg:resourceGroup}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
echo "" >> "${ESTATE_FILE}"

# --- storage_accounts ---
echo "storage_accounts:" >> "${ESTATE_FILE}"
az storage account list --query "[].{name:name, rg:resourceGroup}" -o json 2>/dev/null | \
  jq -r '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\(.rg)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
echo "" >> "${ESTATE_FILE}"

# --- alert_rules ---
echo "alert_rules:" >> "${ESTATE_FILE}"
for rg in $(az group list --query "[].name" -o tsv 2>/dev/null); do
  az monitor metrics alert list -g "$rg" --query "[].{name:name, enabled:enabled}" -o json 2>/dev/null | \
    jq -r --arg rg "$rg" '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\($rg)\"\n    enabled: true"' >> "${ESTATE_FILE}" 2>/dev/null || true
done
echo "" >> "${ESTATE_FILE}"

# --- action_groups ---
echo "action_groups:" >> "${ESTATE_FILE}"
for rg in $(az group list --query "[].name" -o tsv 2>/dev/null); do
  az resource list -g "$rg" --resource-type "Microsoft.Insights/actionGroups" --query "[].{name:name}" -o json 2>/dev/null | \
    jq -r --arg rg "$rg" '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\($rg)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
done
echo "" >> "${ESTATE_FILE}"

# --- cognitive_services (Foundry) ---
echo "cognitive_services:" >> "${ESTATE_FILE}"
for rg in $(az group list --query "[].name" -o tsv 2>/dev/null); do
  az resource list -g "$rg" --resource-type "Microsoft.CognitiveServices/accounts" --query "[].{name:name, kind:kind}" -o json 2>/dev/null | \
    jq -r --arg rg "$rg" '.[] | "  - name: \"\(.name)\"\n    resource_group: \"\($rg)\"\n    kind: \"\(.kind)\""' >> "${ESTATE_FILE}" 2>/dev/null || true
done
echo "" >> "${ESTATE_FILE}"

# =========================================================================
# 5. Summary
# =========================================================================
TOTAL_NAMED=$(grep -c '  - name:' "${ESTATE_FILE}" 2>/dev/null || echo 0)

# Count per section (query_key)
QUERY_KEYS="container_apps container_app_environments container_app_jobs function_apps postgresql_servers key_vaults container_registries front_doors waf_policies virtual_networks dns_zones private_dns_zones private_endpoints application_insights log_analytics_workspaces storage_accounts alert_rules action_groups cognitive_services"

echo "# ======================================" >> "${ESTATE_FILE}"
echo "# Summary" >> "${ESTATE_FILE}"
echo "# ======================================" >> "${ESTATE_FILE}"
cat >> "${ESTATE_FILE}" <<EOF

summary:
  generic_api_count: ${GENERIC_COUNT}
  targeted_resource_count: ${TOTAL_NAMED}
  resource_groups: $(az group list --query "length(@)" -o tsv 2>/dev/null)
  queried_at: "${TIMESTAMP}"
  queried_by: "azure_estate_audit.sh"
  coverage_policy: "${COVERAGE_POLICY}"
  note: "generic_api_count is from az resource list (RBAC-filtered, diagnostic only). targeted_resource_count is the authoritative count."

per_type_counts:
EOF

for key in $QUERY_KEYS; do
  # Count entries in the section
  COUNT=$(awk "/^${key}:/,/^[a-z]/" "${ESTATE_FILE}" | grep -c '  - name:' 2>/dev/null || echo 0)
  echo "  ${key}: ${COUNT}" >> "${ESTATE_FILE}"
done

# =========================================================================
# 6. Coverage report
# =========================================================================
cat > "${COVERAGE_REPORT}" <<COVEOF
Coverage Report — ${TIMESTAMP}
===============================

Tier A (authoritative):    19 resource types queried
Tier B (derived):          5 resource types (auto-managed, not queried)
Tier C (out-of-band):      2 resource types (manual verification only)
Total classified:          26 resource types

Tier A targeted resources: ${TOTAL_NAMED}
Generic API resources:     ${GENERIC_COUNT} (diagnostic only, RBAC-filtered)
Portal resource count:     62 (reference from 2026-04-05)

Gap analysis:
  Tier A covers ${TOTAL_NAMED} of 62 portal resources.
  Tier B accounts for ~6 derived resources (NICs, LB, PIP, ASP).
  Tier C accounts for 2 resources (Workbook, DevOps org).
  Expected total: ~${TOTAL_NAMED} + 6 + 2 = $((TOTAL_NAMED + 8))

COVEOF

if [ -f "${COVERAGE_POLICY}" ]; then
  # Verify every query_key in coverage has a corresponding section in the estate
  echo "Query key parity check:" >> "${COVERAGE_REPORT}"
  MISSING_KEYS=""
  for key in $QUERY_KEYS; do
    if grep -q "query_key: ${key}" "${COVERAGE_POLICY}" 2>/dev/null; then
      echo "  [OK] ${key}" >> "${COVERAGE_REPORT}"
    else
      echo "  [!!] ${key} — not declared in coverage policy" >> "${COVERAGE_REPORT}"
      MISSING_KEYS="${MISSING_KEYS} ${key}"
    fi
  done

  if [ -n "$MISSING_KEYS" ]; then
    echo "" >> "${COVERAGE_REPORT}"
    echo "WARNING: Query keys not in coverage policy:${MISSING_KEYS}" >> "${COVERAGE_REPORT}"
  else
    echo "" >> "${COVERAGE_REPORT}"
    echo "All query keys are declared in coverage policy." >> "${COVERAGE_REPORT}"
  fi
fi

cat "${COVERAGE_REPORT}"

# =========================================================================
# 7. Symlink
# =========================================================================
ln -sf "estate-${TIMESTAMP}.yaml" "${LATEST_LINK}"

# =========================================================================
# 8. Drift detection with critical gating
# =========================================================================
echo "" | tee "${DRIFT_FILE}"

if [ -f "${EXPECTED}" ]; then
  echo "Drift detection against ${EXPECTED}:" | tee -a "${DRIFT_FILE}"
  echo "Queried at: ${TIMESTAMP}" | tee -a "${DRIFT_FILE}"

  EXPECTED_NAMES=$(grep '  - name:' "${EXPECTED}" 2>/dev/null | sed 's/.*name: *"\(.*\)"/\1/' | sort -u)
  ACTUAL_NAMES=$(grep '  - name:' "${ESTATE_FILE}" 2>/dev/null | sed 's/.*name: *"\(.*\)"/\1/' | sort -u)

  MISSING=$(comm -23 <(echo "$EXPECTED_NAMES") <(echo "$ACTUAL_NAMES"))
  UNEXPECTED=$(comm -13 <(echo "$EXPECTED_NAMES") <(echo "$ACTUAL_NAMES"))

  # Critical resource name patterns (from critical_types in coverage policy)
  # PG, KV, ACA core, PE, Private DNS, FD, WAF, ACR
  CRITICAL_PATTERN='^(pg-|kv-|ipai-odoo-dev-|ipai-odoo-ha-|pe-|afd-|waf|acr|privatelink\.|ipai-build-agent)'

  if [ -n "$MISSING" ]; then
    echo "" | tee -a "${DRIFT_FILE}"
    echo "MISSING (expected but not found):" | tee -a "${DRIFT_FILE}"
    echo "$MISSING" | sed 's/^/  - /' | tee -a "${DRIFT_FILE}"

    CRITICAL_MISSING=$(echo "$MISSING" | grep -E "$CRITICAL_PATTERN" || true)
    if [ -n "$CRITICAL_MISSING" ]; then
      echo "" | tee -a "${DRIFT_FILE}"
      echo "!! CRITICAL DRIFT — missing critical authoritative resources:" | tee -a "${DRIFT_FILE}"
      echo "$CRITICAL_MISSING" | sed 's/^/  !! /' | tee -a "${DRIFT_FILE}"
      EXIT_CODE=1
    fi
  fi

  if [ -n "$UNEXPECTED" ]; then
    echo "" | tee -a "${DRIFT_FILE}"
    echo "UNEXPECTED (found but not in expected):" | tee -a "${DRIFT_FILE}"
    echo "$UNEXPECTED" | sed 's/^/  - /' | tee -a "${DRIFT_FILE}"

    CRITICAL_UNEXPECTED=$(echo "$UNEXPECTED" | grep -E "$CRITICAL_PATTERN" || true)
    if [ -n "$CRITICAL_UNEXPECTED" ]; then
      echo "" | tee -a "${DRIFT_FILE}"
      echo "!! WARNING — unexpected critical resources (may be legitimate new deploy):" | tee -a "${DRIFT_FILE}"
      echo "$CRITICAL_UNEXPECTED" | sed 's/^/  ?? /' | tee -a "${DRIFT_FILE}"
      # Warn only, don't fail — could be a new intentional deployment
    fi
  fi

  if [ -z "$MISSING" ] && [ -z "$UNEXPECTED" ]; then
    echo "NO DRIFT — actual matches expected." | tee -a "${DRIFT_FILE}"
  fi
else
  echo "No expected estate file at ${EXPECTED}. Skipping drift detection." | tee "${DRIFT_FILE}"
  echo "To enable: copy ${LATEST_LINK} to ${EXPECTED} after manual review." | tee -a "${DRIFT_FILE}"
fi

# =========================================================================
# 9. Final output
# =========================================================================
echo ""
echo "============================================="
echo "Estate audit complete"
echo "  Inventory: ${ESTATE_FILE}"
echo "  Latest:    ${LATEST_LINK}"
echo "  Drift:     ${DRIFT_FILE}"
echo "  Coverage:  ${COVERAGE_REPORT}"
echo "  Resources: ${TOTAL_NAMED} authoritative (${GENERIC_COUNT} generic API)"
if [ ${EXIT_CODE} -ne 0 ]; then
  echo "  STATUS:    FAIL — critical drift detected"
else
  echo "  STATUS:    PASS"
fi
echo "============================================="

exit ${EXIT_CODE}
