// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/app/close" | "/app/close/audit" | "/app/close/compliance" | "/app/close/tasks" | "/login" | "/logout" | "/projects" | "/projects/[projectId]/backups" | "/projects/[projectId]/branches" | "/projects/[projectId]/builds" | "/projects/[projectId]/builds/[buildId]/editor" | "/projects/[projectId]/builds/[buildId]/logs" | "/projects/[projectId]/builds/[buildId]/monitor" | "/projects/[projectId]/builds/[buildId]/shell" | "/projects/[projectId]/monitor" | "/projects/[projectId]/settings" | "/projects/[projectId]/upgrade"
type AppRouteHandlerRoutes = "/api/supabase-proxy/[...path]"
type PageRoutes = never
type LayoutRoutes = "/" | "/app" | "/projects/[projectId]" | "/projects/[projectId]/builds/[buildId]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/supabase-proxy/[...path]": { "path": string[]; }
  "/app": {}
  "/app/close": {}
  "/app/close/audit": {}
  "/app/close/compliance": {}
  "/app/close/tasks": {}
  "/login": {}
  "/logout": {}
  "/projects": {}
  "/projects/[projectId]": { "projectId": string; }
  "/projects/[projectId]/backups": { "projectId": string; }
  "/projects/[projectId]/branches": { "projectId": string; }
  "/projects/[projectId]/builds": { "projectId": string; }
  "/projects/[projectId]/builds/[buildId]": { "projectId": string; "buildId": string; }
  "/projects/[projectId]/builds/[buildId]/editor": { "projectId": string; "buildId": string; }
  "/projects/[projectId]/builds/[buildId]/logs": { "projectId": string; "buildId": string; }
  "/projects/[projectId]/builds/[buildId]/monitor": { "projectId": string; "buildId": string; }
  "/projects/[projectId]/builds/[buildId]/shell": { "projectId": string; "buildId": string; }
  "/projects/[projectId]/monitor": { "projectId": string; }
  "/projects/[projectId]/settings": { "projectId": string; }
  "/projects/[projectId]/upgrade": { "projectId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
  "/projects/[projectId]": never
  "/projects/[projectId]/builds/[buildId]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
