# -*- coding: utf-8 -*-
{
    "name": "IPAI Finance Project Hybrid (IM1/IM2 + BIR + Month-End Generators)",
    "summary": "Turns finance phases into IM projects, seeds finance directory/BIR schedule, generates month-end + compliance tasks, and adds analytics dashboards.",
    "version": "18.0.1.0.0",
    "category": "Project",
    "license": "LGPL-3",
    "author": "InsightPulseAI",
    "website": "https://insightpulseai.com",
    "depends": ["project", "mail"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/menu.xml",
        "views/finance_directory_views.xml",
        "views/bir_schedule_views.xml",
        "views/task_template_views.xml",
        "views/project_views.xml",
        "views/task_views.xml",
        "views/dashboard_views.xml",
        "views/seed_wizard_views.xml",
        "data/ir_cron.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
