# Copyright 2026 InsightPulseAI
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
{
    "name": "IPAI Enterprise Bridge",
    "summary": "Replace Odoo Enterprise/IAP features with CE+OCA alternatives",
    "version": "18.0.1.0.0",
    "category": "Technical",
    "author": "InsightPulseAI",
    "website": "https://github.com/jgtolentino/odoo-ce",
    "license": "LGPL-3",
    "depends": [
        "base",
        "base_setup",
        "mail",
        "auth_oauth",
        "fetchmail",
        "web",
        "hr_expense",
        "maintenance",
        "project",
    ],
    "external_dependencies": {
        "python": [
            "requests",
            "paho-mqtt",
        ],
    },
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/groups.xml",
        "data/sequences.xml",
        "data/scheduled_actions.xml",
        "data/mail_server.xml",
        "data/oauth_providers.xml",
        "data/enterprise_bridge_data.xml",
        "views/res_config_settings_views.xml",
        "views/iot_device_views.xml",
        "views/ipai_close_views.xml",
        "views/ipai_policy_views.xml",
        "views/product_views.xml",
        "views/enterprise_bridge_views.xml",
    ],
    "demo": [
        "demo/demo_data.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
