# -*- coding: utf-8 -*-
{
    "name": "IPAI Finance PPM",
    "summary": "Finance Project Portfolio Management (Notion Parity).",
    "version": "18.0.1.1.0",
    "category": "Accounting/Finance",
    "author": "InsightPulse AI",
    "website": "https://github.com/jgtolentino/odoo-ce/tree/18.0/addons/ipai/ipai_finance_ppm",
    "license": "AGPL-3",
    "depends": [
        "base",
        "mail",
        "project",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/finance_ppm_groups.xml",
        "views/finance_person_views.xml",
        "views/finance_bir_deadline_views.xml",
        "views/finance_task_views.xml",
        "views/bir_schedule_views.xml",
        "views/ppm_dashboard_views.xml",
        "views/project_task_views.xml",
        "views/finance_kanban_views.xml",
        "views/menus.xml",
        "data/finance_person_seed.xml",
        "data/bir_schedule_seed.xml",
        "data/finance_okr_seed.xml",
        "data/finance_bir_2026_seed.xml",
        "data/finance_month_end_seed.xml",
        "data/mail_server_seed.xml",
        "data/reminder_system_cron.xml",
        "data/finance_cron.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ipai_finance_ppm/static/src/js/ppm_dashboard.js",
            "ipai_finance_ppm/static/src/js/semantic-search/api.js",
            "ipai_finance_ppm/static/src/js/semantic-search/MonthlyRevenueSearch.js",
            "ipai_finance_ppm/static/src/xml/monthly_revenue_search.xml",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
