# -*- coding: utf-8 -*-
{
    'name': 'IPAI BIR Compliance',
    'version': '18.0.1.0.0',
    'category': 'Accounting/Localization',
    'sequence': 81,
    'summary': 'Philippine BIR compliance — form registry, deadline engine, filing calendar, evidence tracking',
    'author': 'InsightPulse AI',
    'website': 'https://insightpulseai.com',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'account',
        'calendar',
        'mail',
        'ipai_branch_profile',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/bir_forms.xml',
        'data/bir_deadline_rules.xml',
        'data/bir_service_endpoints.xml',
        'data/ir_cron.xml',
        'views/bir_form_views.xml',
        'views/bir_obligation_views.xml',
        'views/bir_period_views.xml',
        'views/bir_filing_views.xml',
        'views/bir_service_endpoint_views.xml',
        'views/menu.xml',
    ],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}
