#!/bin/bash
# Install all OCA modules required for EE parity
# Usage: ./scripts/install_oca_parity.sh [--clone-only|--install-only]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
OCA_DIR="${REPO_ROOT}/addons/oca"
ODOO_VERSION="${ODOO_VERSION:-19.0}"
DB_NAME="${DB_NAME:-odoo_core}"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# OCA repositories and modules for EE parity
declare -A OCA_REPOS=(
    ["account-financial-tools"]="account_asset_management"
    ["mis-builder"]="mis_builder,mis_builder_budget"
    ["account-consolidation"]="account_consolidation"
    ["account-analytic"]="analytic_tag_dimension"
    ["dms"]="dms,dms_field"
    ["hr"]="hr_appraisal_survey"
    ["payroll"]="payroll,payroll_account"
    ["web"]="web_timeline,web_widget_many2many_tags_multi_selection"
    ["project"]="project_timeline,project_forecast_line"
    ["manufacture"]="quality_control_oca"
    ["social"]="sms_no_iap"
)

clone_oca_repos() {
    log_info "Cloning OCA repositories for Odoo ${ODOO_VERSION}..."
    mkdir -p "$OCA_DIR"

    for repo in "${!OCA_REPOS[@]}"; do
        local repo_path="${OCA_DIR}/${repo}"
        local repo_url="https://github.com/OCA/${repo}.git"

        if [[ -d "$repo_path" ]]; then
            log_info "Repository ${repo} already exists, pulling latest..."
            (cd "$repo_path" && git fetch origin && git checkout "${ODOO_VERSION}" 2>/dev/null || git checkout -b "${ODOO_VERSION}" "origin/${ODOO_VERSION}" 2>/dev/null || log_warn "Branch ${ODOO_VERSION} not available for ${repo}")
        else
            log_info "Cloning ${repo}..."
            if git clone --branch "${ODOO_VERSION}" --depth 1 "$repo_url" "$repo_path" 2>/dev/null; then
                log_info "Successfully cloned ${repo} (${ODOO_VERSION})"
            else
                log_warn "Branch ${ODOO_VERSION} not found, trying 18.0..."
                git clone --branch "18.0" --depth 1 "$repo_url" "$repo_path" 2>/dev/null || log_error "Failed to clone ${repo}"
            fi
        fi
    done

    log_info "OCA repositories cloned successfully"
}

collect_modules() {
    local modules=""
    for repo in "${!OCA_REPOS[@]}"; do
        local repo_modules="${OCA_REPOS[$repo]}"
        if [[ -n "$modules" ]]; then
            modules="${modules},${repo_modules}"
        else
            modules="$repo_modules"
        fi
    done
    echo "$modules"
}

install_modules() {
    local modules
    modules=$(collect_modules)
    log_info "Installing OCA modules: ${modules}"

    # Build addons path
    local addons_path="${REPO_ROOT}/addons"
    for repo in "${!OCA_REPOS[@]}"; do
        addons_path="${addons_path},${OCA_DIR}/${repo}"
    done

    # Check if running in Docker
    if [[ -f /.dockerenv ]] || grep -q docker /proc/1/cgroup 2>/dev/null; then
        log_info "Running in Docker environment"
        odoo -d "${DB_NAME}" -i "${modules}" --stop-after-init --addons-path="${addons_path}"
    elif command -v docker &>/dev/null && docker ps -q --filter "name=odoo" 2>/dev/null | grep -q .; then
        log_info "Using Docker container"
        docker exec -it odoo-core odoo -d "${DB_NAME}" -i "${modules}" --stop-after-init
    else
        log_info "Running locally"
        if command -v odoo &>/dev/null; then
            odoo -d "${DB_NAME}" -i "${modules}" --stop-after-init --addons-path="${addons_path}"
        elif command -v odoo-bin &>/dev/null; then
            odoo-bin -d "${DB_NAME}" -i "${modules}" --stop-after-init --addons-path="${addons_path}"
        else
            log_error "Odoo binary not found. Please install Odoo or run in Docker."
            exit 1
        fi
    fi

    log_info "OCA modules installed successfully"
}

generate_requirements() {
    log_info "Generating OCA requirements.txt..."
    local req_file="${REPO_ROOT}/requirements-oca.txt"

    cat > "$req_file" << 'EOF'
# OCA module dependencies for EE parity
# Generated by install_oca_parity.sh

# MIS Builder
xlsxwriter>=1.0
xlrd>=1.0

# DMS
python-magic>=0.4.24

# Payroll
dateutil>=2.8

# Quality Control
qrcode>=7.0
EOF

    log_info "Generated ${req_file}"
}

print_summary() {
    echo ""
    echo "=========================================="
    echo "OCA EE PARITY INSTALLATION SUMMARY"
    echo "=========================================="
    echo ""
    echo "Repositories cloned: ${#OCA_REPOS[@]}"
    echo "Modules to install: $(collect_modules | tr ',' '\n' | wc -l)"
    echo ""
    echo "Modules:"
    for repo in "${!OCA_REPOS[@]}"; do
        echo "  ${repo}:"
        echo "    - ${OCA_REPOS[$repo]//,/$'\n    - '}"
    done
    echo ""
    echo "Run with --install-only to install modules"
    echo "=========================================="
}

main() {
    local mode="${1:-all}"

    case "$mode" in
        --clone-only)
            clone_oca_repos
            generate_requirements
            print_summary
            ;;
        --install-only)
            install_modules
            ;;
        --summary)
            print_summary
            ;;
        all|"")
            clone_oca_repos
            generate_requirements
            install_modules
            print_summary
            ;;
        *)
            echo "Usage: $0 [--clone-only|--install-only|--summary]"
            exit 1
            ;;
    esac
}

main "$@"
