#!/usr/bin/env bash
# ============================================================================
# sync-tokens.sh - Sync design tokens to Odoo theme addon
# ============================================================================
# Copies tokens.scss from packages/ipai-design-tokens to the Odoo theme addon.
# Run this after updating tokens to keep Odoo theme in sync.
#
# Usage:
#   ./scripts/sync-tokens.sh
#
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TOKENS_PKG="${REPO_ROOT}/packages/ipai-design-tokens"
ODOO_THEME="${REPO_ROOT}/addons/ipai_web_theme_chatgpt/static/src/scss"

echo "=== IPAI Design Token Sync ==="

# Check source exists
if [ ! -f "${TOKENS_PKG}/tokens.scss" ]; then
    echo "ERROR: tokens.scss not found at ${TOKENS_PKG}/tokens.scss"
    exit 1
fi

# Ensure target directory exists
mkdir -p "${ODOO_THEME}"

# Create a header comment noting the source
cat > "${ODOO_THEME}/tokens_shared.scss" <<'HEADER'
// ============================================================================
// SHARED DESIGN TOKENS - DO NOT EDIT DIRECTLY
// ============================================================================
// This file is auto-generated by scripts/sync-tokens.sh
// Edit packages/ipai-design-tokens/tokens.scss and re-run sync script.
// ============================================================================

HEADER

# Append the token content
cat "${TOKENS_PKG}/tokens.scss" >> "${ODOO_THEME}/tokens_shared.scss"

echo "OK: synced tokens.scss -> ${ODOO_THEME}/tokens_shared.scss"
echo ""
echo "Next steps:"
echo "  1. Restart Odoo to reload assets"
echo "  2. Hard refresh browser (Ctrl+Shift+R) or use ?debug=assets"
echo ""
