version: 1
generated_at: '2026-03-08T08:23:43.220063+00:00'
environments:
- provider: github
  environment: sandbox
  repo: .github
  class: dev
  canonical: true
- provider: github
  environment: Preview
  repo: .github
  class: preview
  canonical: true
- provider: github
  environment: audit
  repo: .github
  class: prod
  canonical: true
- provider: github
  environment: Production
  repo: .github
  class: prod
  canonical: true
- provider: github
  environment: staging
  repo: .github
  class: staging
  canonical: true
- provider: github
  environment: databricks-dev
  repo: odoo
  class: dev
  canonical: true
- provider: github
  environment: dev
  repo: odoo
  class: dev
  canonical: true
- provider: github
  environment: odoo-dev
  repo: odoo
  class: dev
  canonical: true
- provider: github
  environment: Preview – insightpulseai-web
  repo: odoo
  class: preview
  canonical: true
- provider: github
  environment: Preview – odooops-console
  repo: odoo
  class: preview
  canonical: true
- provider: github
  environment: databricks-production
  repo: odoo
  class: prod
  canonical: true
- provider: github
  environment: github-pages
  repo: odoo
  class: prod
  canonical: true
- provider: github
  environment: odoo-production
  repo: odoo
  class: prod
  canonical: true
- provider: github
  environment: Production – insightpulseai-web
  repo: odoo
  class: prod
  canonical: true
- provider: github
  environment: Production – odooops-console
  repo: odoo
  class: prod
  canonical: true
- provider: github
  environment: databricks-staging
  repo: odoo
  class: staging
  canonical: true
- provider: github
  environment: odoo-staging
  repo: odoo
  class: staging
  canonical: true
- provider: github
  environment: github-pages
  repo: roadmap
  class: prod
  canonical: true
