/**
 * IPAI Brand Design Tokens - TypeScript/JavaScript Export
 *
 * Version: 1.0.0
 * Generated from: pkgs/ipai-design-tokens/tokens.json
 *
 * Usage:
 *   import { colors, radius, space } from '@ipai/design-tokens/ipai-brand';
 *   const primaryColor = colors.brand.navy;
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Edit tokens.json and regenerate exports
 */

export const colors = {
  brand: {
    navy: '#0F2A44',
    navyDeep: '#0A1E33',
    ink: '#0A1E33',
  },
  accent: {
    green: '#7BC043',
    teal: '#64B9CA',
    amber: '#F6C445',
  },
  surface: {
    bg: '#E7EDF5',
    bg2: '#E1E8F2',
    card: '#FFFFFF',
  },
  text: {
    primary: '#0B1F33',
    secondary: '#5E6B7C',
    onDark: '#FFFFFF',
  },
  border: {
    subtle: '#D7DDE6',
    hairline: 'rgba(0, 0, 0, 0.08)',
  },
  state: {
    success: '#7BC043',
    info: '#64B9CA',
    warning: '#F6C445',
    danger: '#E5484D',
  },
} as const;

export const radius = {
  card: '20px',
  panel: '28px',
  pill: '999px',
  input: '16px',
} as const;

export const space = {
  1: '4px',
  2: '8px',
  3: '12px',
  4: '16px',
  6: '24px',
  8: '32px',
  12: '48px',
  16: '64px',
} as const;

export const shadow = {
  card: '0 10px 26px rgba(21, 36, 58, 0.10)',
  elevated: '0 16px 38px rgba(21, 36, 58, 0.12)',
  floating: '0 24px 48px rgba(21, 36, 58, 0.15)',
} as const;

export const typography = {
  fontFamily: {
    ui: "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    mono: "ui-monospace, 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, monospace",
  },
  fontSize: {
    display: '48px',
    h1: '36px',
    h2: '28px',
    h3: '20px',
    body: '16px',
    caption: '12px',
  },
  lineHeight: {
    display: 1.1,
    heading: 1.2,
    body: 1.5,
    caption: 1.3,
  },
  fontWeight: {
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },
} as const;

export const transition = {
  duration: {
    fast: '100ms',
    normal: '200ms',
    slow: '350ms',
  },
  easing: {
    in: 'ease-in',
    out: 'ease-out',
    inOut: 'ease-in-out',
  },
} as const;

/**
 * Complete token object combining all categories
 */
export const tokens = {
  colors,
  radius,
  space,
  shadow,
  typography,
  transition,
} as const;

/**
 * Type definitions for token access
 */
export type Colors = typeof colors;
export type Radius = typeof radius;
export type Space = typeof space;
export type Shadow = typeof shadow;
export type Typography = typeof typography;
export type Transition = typeof transition;
export type Tokens = typeof tokens;

/**
 * Helper function to get CSS variable names
 */
export function toCSSVar(path: string): string {
  return `var(--ipai-${path.replace(/\./g, '-')})`;
}

/**
 * Helper function to generate CSS variable declarations
 */
export function generateCSSVars(): Record<string, string> {
  const vars: Record<string, string> = {};

  // Colors
  Object.entries(colors).forEach(([category, shades]) => {
    Object.entries(shades).forEach(([shade, value]) => {
      vars[`--ipai-${category}-${shade}`] = value;
    });
  });

  // Radius
  Object.entries(radius).forEach(([key, value]) => {
    vars[`--ipai-radius-${key}`] = value;
  });

  // Space
  Object.entries(space).forEach(([key, value]) => {
    vars[`--ipai-space-${key}`] = value;
  });

  // Shadow
  Object.entries(shadow).forEach(([key, value]) => {
    vars[`--ipai-shadow-${key}`] = value;
  });

  return vars;
}

/**
 * Default export for convenience
 */
export default tokens;
