{
    'name': 'IPAI Month-End Closing & BIR Tax Filing',
    'version': '18.0.1.0.0',
    'category': 'Project/PPM',
    'summary': 'Finance Month-End Close Command Center with BIR Tax Compliance',
    'author': 'InsightPulse AI',
    'website': 'https://insightpulseai.net',
    'license': 'AGPL-3',
    'depends': [
        'project',
        'resource',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/menus.xml',
        'data/project_tags.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/project_milestone.xml',
        'data/project_task_closing.xml',
        'data/project_task_tax.xml',
        'data/resource_calendar_leaves.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
