# -*- coding: utf-8 -*-
"""
Control Room Artifact Model
============================

Tracks outputs, exports, and files generated by pipeline runs.
"""

from odoo import api, fields, models


class ControlArtifact(models.Model):
    """
    Control Artifact

    Represents an output file or data object produced
    by a pipeline run or associated with a project.
    """

    _name = "control.artifact"
    _description = "Control Artifact"
    _order = "create_date DESC"

    # Identity
    name = fields.Char(
        string="Artifact Name",
        required=True,
    )
    kind = fields.Selection(
        [
            ("csv", "CSV"),
            ("json", "JSON"),
            ("pdf", "PDF"),
            ("image", "Image"),
            ("model", "ML Model"),
            ("zip", "Archive"),
            ("report", "Report"),
            ("log", "Log File"),
            ("other", "Other"),
        ],
        string="Kind",
        default="other",
        required=True,
    )

    # Relationships
    run_id = fields.Many2one(
        "control.run",
        string="Run",
        ondelete="cascade",
        index=True,
    )
    project_id = fields.Many2one(
        "project.project",
        string="Project",
        index=True,
    )
    company_id = fields.Many2one(
        "res.company",
        string="Company",
        default=lambda self: self.env.company,
    )

    # Storage
    storage = fields.Selection(
        [
            ("attachment", "Odoo Attachment"),
            ("s3", "S3 / Object Storage"),
            ("gdrive", "Google Drive"),
            ("supabase", "Supabase Storage"),
            ("external", "External URL"),
        ],
        string="Storage Backend",
        default="attachment",
        required=True,
    )
    attachment_id = fields.Many2one(
        "ir.attachment",
        string="Attachment",
        help="Odoo attachment for local storage",
    )
    uri = fields.Char(
        string="External URI",
        help="S3 URL, GDrive link, or external storage URI",
    )

    # Metadata
    metadata_json = fields.Text(
        string="Metadata (JSON)",
        help="Artifact metadata (schema, row count, etc.)",
    )
    checksum = fields.Char(
        string="Checksum (SHA256)",
    )
    size_bytes = fields.Integer(
        string="Size (bytes)",
    )
    mime_type = fields.Char(
        string="MIME Type",
    )

    # Description
    description = fields.Text(
        string="Description",
    )

    # Timestamps
    generated_at = fields.Datetime(
        string="Generated At",
        default=fields.Datetime.now,
    )
    expires_at = fields.Datetime(
        string="Expires At",
        help="Optional expiration timestamp for cleanup",
    )

    @api.model
    def create_from_attachment(self, attachment, run_id=None, kind="other"):
        """Create artifact from an ir.attachment"""
        return self.create({
            "name": attachment.name,
            "kind": kind,
            "run_id": run_id,
            "storage": "attachment",
            "attachment_id": attachment.id,
            "size_bytes": attachment.file_size,
            "mime_type": attachment.mimetype,
            "checksum": attachment.checksum,
        })

    def action_download(self):
        """Return download action for the artifact"""
        self.ensure_one()
        if self.storage == "attachment" and self.attachment_id:
            return {
                "type": "ir.actions.act_url",
                "url": f"/web/content/{self.attachment_id.id}?download=true",
                "target": "new",
            }
        elif self.uri:
            return {
                "type": "ir.actions.act_url",
                "url": self.uri,
                "target": "new",
            }
        return False
