{
    "name": "IPAI Meta Finance PPM",
    "summary": "Dependency-only install set for Finance PPM stack",
    "version": "19.0.1.0.0",
    "author": "InsightPulseAI",
    "license": "LGPL-3",
    "category": "IPAI/Meta",
    "depends": [
        "base_technical_features",
        "web_responsive",
        "queue_job",
        "date_range",
        "account_financial_report",
        "mis_builder",
        "dms",
        "ipai_finance_ppm",
        "ipai_finance_close_seed",
        "ipai_bir_tax_compliance",
        "ipai_bir_notifications",
        "ipai_bir_plane_sync",
        "ipai_slack_connector",
        "ipai_pulser_connector",
    ],
    "data": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}
