var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f422645b._.js")
R.c("server/chunks/ssr/Documents_GitHub_Insightpulseai_odoo_templates_odooops-console_856a39da._.js")
R.c("server/chunks/ssr/bfc07_next_dist_esm_build_templates_app-page_50981107.js")
R.c("server/chunks/ssr/[root-of-the-server]__60705b28._.js")
R.c("server/chunks/ssr/[root-of-the-server]__20fb1ffe._.js")
R.c("server/chunks/ssr/bfc07_next_dist_1606ad85._.js")
R.c("server/chunks/ssr/Documents_GitHub_Insightpulseai_odoo_templates_odooops-console_app_7da3043f._.js")
R.c("server/chunks/ssr/Documents_GitHub_Insightpulseai_odoo_templates_odooops-console_app_b96dd292._.js")
R.c("server/chunks/ssr/Documents_GitHub_Insightpulseai_odoo_templates_odooops-console_app_eaef2e21._.js")
R.c("server/chunks/ssr/[root-of-the-server]__196e8450._.js")
R.c("server/chunks/ssr/bfc07_next_dist_client_components_b2d31f42._.js")
R.c("server/chunks/ssr/bfc07_next_dist_client_components_builtin_forbidden_000bf447.js")
R.c("server/chunks/ssr/93f3e_odooops-console__next-internal_server_app__not-found_page_actions_7f3f1896.js")
R.m(77005)
module.exports=R.m(77005).exports
